const quotesArray = [
    { "quote": "The only way to do great work is to love what you do. – Steve Jobs" },
    { "quote": "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. – Albert Schweitzer" },
    { "quote": "Believe you can and you're halfway there. – Theodore Roosevelt" },
    { "quote": "You miss 100% of the shots you don’t take. – Wayne Gretzky" },
    { "quote": "The best way to predict the future is to invent it. – Alan Kay" },
    { "quote": "Do not wait to strike till the iron is hot, but make it hot by striking. – William Butler Yeats" },
    { "quote": "Your time is limited, so don’t waste it living someone else’s life. – Steve Jobs" },
    { "quote": "Act as if what you do makes a difference. It does. – William James" },
    { "quote": "Success usually comes to those who are too busy to be looking for it. – Henry David Thoreau" },
    { "quote": "Don’t watch the clock; do what it does. Keep going. – Sam Levenson" },
    { "quote": "The only limit to our realization of tomorrow is our doubts of today. – Franklin D. Roosevelt" },
    { "quote": "In the middle of every difficulty lies opportunity. – Albert Einstein" },
    { "quote": "Everything you’ve ever wanted is on the other side of fear. – George Addair" },
    { "quote": "Opportunities don't happen. You create them. – Chris Grosser" },
    { "quote": "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart. – Roy T. Bennett" },
    { "quote": "Success is not in what you have, but who you are. – Bo Bennett" },
    { "quote": "The harder you work for something, the greater you’ll feel when you achieve it. – Unknown" },
    { "quote": "Dream it. Wish it. Do it. – Unknown" },
    { "quote": "Success doesn’t just find you. You have to go out and get it. – Unknown" },
    { "quote": "The key to success is to focus on goals, not obstacles. – Unknown" },
    { "quote": "Dream bigger. Do bigger. – Unknown" },
    { "quote": "Don't stop when you're tired. Stop when you're done. – Unknown" },
    { "quote": "Wake up with determination. Go to bed with satisfaction. – Unknown" },
    { "quote": "Do something today that your future self will thank you for. – Unknown" },
    { "quote": "Little things make big days. Great things take time. Be patient. – Unknown" },
    { "quote": "It’s going to be hard, but hard does not mean impossible. – Unknown" },
    { "quote": "Push yourself, because no one else is going to do it for you. – Unknown" },
    { "quote": "Great things never come from comfort zones. – Unknown" },
    { "quote": "Dream it. Believe it. Build it. – Unknown" },
    { "quote": "Success doesn’t just find you. You have to go out and get it. – Unknown" },
    { "quote": "The harder you work for something, the greater you’ll feel when you achieve it. – Unknown" },
    { "quote": "Dream bigger. Do bigger. – Unknown" },
    { "quote": "Don’t wait for opportunity. Create it. – Unknown" },
    { "quote": "The key to success is to focus on goals, not obstacles. – Unknown" },
    { "quote": "Dream it. Wish it. Do it. – Unknown" },
    { "quote": "Success doesn’t just find you. You have to go out and get it. – Unknown" },
    { "quote": "Work hard in silence, let your success be your noise. – Frank Ocean" },
    { "quote": "Rise above the storm and you will find the sunshine. – Mario Fernandez" },
    { "quote": "Don’t be afraid to give up the good to go for the great. – John D. Rockefeller" },
    { "quote": "I find that the harder I work, the more luck I seem to have. – Thomas Jefferson" },
    { "quote": "Success is not the absence of failure; it’s the persistence through failure. – Aisha Tyler" },
    { "quote": "Hardships often prepare ordinary people for an extraordinary destiny. – C.S. Lewis" },
    { "quote": "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. – Christian D. Larson" },
    { "quote": "The future belongs to those who believe in the beauty of their dreams. – Eleanor Roosevelt" },
    { "quote": "You are never too old to set another goal or to dream a new dream. – C.S. Lewis" },
    { "quote": "The only way to achieve the impossible is to believe it is possible. – Charles Kingsleigh" },
    { "quote": "Success is going from failure to failure without losing your enthusiasm. – Winston Churchill" },
    { "quote": "The only limit to our realization of tomorrow is our doubts of today. – Franklin D. Roosevelt" },
    { "quote": "Act as if what you do makes a difference. It does. – William James" },
    { "quote": "We may encounter many defeats but we must not be defeated. – Maya Angelou" },
    { "quote": "You don’t have to be great to start, but you have to start to be great. – Zig Ziglar" },
    { "quote": "Everything you’ve ever wanted is on the other side of fear. – George Addair" },
    { "quote": "Success is not final, failure is not fatal: It is the courage to continue that counts. – Winston Churchill" },
    { "quote": "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart. – Roy T. Bennett" },
    { "quote": "You are never too old to set another goal or to dream a new dream. – C.S. Lewis" },
    { "quote": "The best time to plant a tree was 20 years ago. The second best time is now. – Chinese Proverb" },
    { "quote": "The only limit to our realization of tomorrow is our doubts of today. – Franklin D. Roosevelt" },
    { "quote": "Don’t let yesterday take up too much of today. – Will Rogers" },
    { "quote": "You do not find the happy life. You make it. – Camilla E. Kimball" },
    { "quote": "The only way to do great work is to love what you do. – Steve Jobs" },
    { "quote": "Success usually comes to those who are too busy to be looking for it. – Henry David Thoreau" },
    { "quote": "Don’t watch the clock; do what it does. Keep going. – Sam Levenson" },
    { "quote": "The future belongs to those who believe in the beauty of their dreams. – Eleanor Roosevelt" },
    { "quote": "The only way to achieve the impossible is to believe it is possible. – Charles Kingsleigh" },
    { "quote": "Hardships often prepare ordinary people for an extraordinary destiny. – C.S. Lewis" },
    { "quote": "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. – Christian D. Larson" },
    { "quote": "The future belongs to those who believe in the beauty of their dreams. – Eleanor Roosevelt" },
    { "quote": "You are never too old to set another goal or to dream a new dream. – C.S. Lewis" },
    { "quote": "Success is going from failure to failure without losing your enthusiasm. – Winston Churchill" },
    { "quote": "The only limit to our realization of tomorrow is our doubts of today. – Franklin D. Roosevelt" },
    { "quote": "Act as if what you do makes a difference. It does. – William James" },
    { "quote": "We may encounter many defeats but we must not be defeated. – Maya Angelou" },
    { "quote": "You don’t have to be great to start, but you have to start to be great. – Zig Ziglar" },
    { "quote": "Everything you’ve ever wanted is on the other side of fear. – George Addair" },
    { "quote": "Success is not final, failure is not fatal: It is the courage to continue that counts. – Winston Churchill" },
    { "quote": "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart. – Roy T. Bennett" },
    { "quote": "You are never too old to set another goal or to dream a new dream. – C.S. Lewis" },
    { "quote": "The best time to plant a tree was 20 years ago. The second best time is now. – Chinese Proverb" },
    { "quote": "The only limit to our realization of tomorrow is our doubts of today. "},
        
            { "quote": "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. – Christian D. Larson" },
            { "quote": "The only way to do great work is to love what you do. – Steve Jobs" },
            { "quote": "Success is not final, failure is not fatal: It is the courage to continue that counts. – Winston Churchill" },
            { "quote": "The best way to predict your future is to create it. – Peter Drucker" },
            { "quote": "You miss 100% of the shots you don’t take. – Wayne Gretzky" },
            { "quote": "Hardships often prepare ordinary people for an extraordinary destiny. – C.S. Lewis" },
            { "quote": "Don’t watch the clock; do what it does. Keep going. – Sam Levenson" },
            { "quote": "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. – Albert Schweitzer" },
            { "quote": "It does not matter how slowly you go as long as you do not stop. – Confucius" },
            { "quote": "Dream big and dare to fail. – Norman Vaughan" },
            { "quote": "The only limit to our realization of tomorrow is our doubts of today. – Franklin D. Roosevelt" },
            { "quote": "What lies behind us and what lies before us are tiny matters compared to what lies within us. – Ralph Waldo Emerson" },
            { "quote": "Act as if what you do makes a difference. It does. – William James" },
            { "quote": "The only person you are destined to become is the person you decide to be. – Ralph Waldo Emerson" },
            { "quote": "Believe you can and you're halfway there. – Theodore Roosevelt" },
            { "quote": "The future belongs to those who believe in the beauty of their dreams. – Eleanor Roosevelt" },
            { "quote": "You are never too old to set another goal or to dream a new dream. – C.S. Lewis" },
            { "quote": "Everything you’ve ever wanted is on the other side of fear. – George Addair" },
            { "quote": "We may encounter many defeats but we must not be defeated. – Maya Angelou" },
            { "quote": "The only way to achieve the impossible is to believe it is possible. – Charles Kingsleigh" },
            { "quote": "What you get by achieving your goals is not as important as what you become by achieving your goals. – Zig Ziglar" },
            { "quote": "Success usually comes to those who are too busy to be looking for it. – Henry David Thoreau" },
            { "quote": "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart. – Roy T. Bennett" },
            { "quote": "Keep your face always toward the sunshine—and shadows will fall behind you. – Walt Whitman" },
            { "quote": "The only place where success comes before work is in the dictionary. – Vidal Sassoon" },
            { "quote": "Don’t count the days, make the days count. – Muhammad Ali" },
            { "quote": "Success is the sum of small efforts, repeated day in and day out. – Robert Collier" },
            { "quote": "It always seems impossible until it’s done. – Nelson Mandela" },
            { "quote": "You have within you right now, everything you need to deal with whatever the world can throw at you. – Brian Tracy" },
            { "quote": "Don’t limit your challenges. Challenge your limits. – Jerry Dunn" },
            { "quote": "Do what you can, with what you have, where you are. – Theodore Roosevelt" },
            { "quote": "The harder the struggle, the more glorious the triumph. – Swami Sivananda" },
            { "quote": "The difference between who you are and who you want to be is what you do. – Charles Duhigg" },
            { "quote": "Opportunities don’t happen. You create them. – Chris Grosser" },
            { "quote": "The only thing standing between you and your goal is the story you keep telling yourself as to why you can’t achieve it. – Jordan Belfort" },
            { "quote": "Start where you are. Use what you have. Do what you can. – Arthur Ashe" },
            { "quote": "Everything you’ve ever dreamed of is on the other side of fear. – George Addair" },
            { "quote": "Success is not how high you have climbed, but how you make a positive difference to the world. – Roy T. Bennett" },
            { "quote": "What you do today can improve all your tomorrows. – Ralph Marston" },
            { "quote": "Aim for the moon. If you miss, you may hit a star. – W. Clement Stone" },
            { "quote": "Don’t quit. Suffer now and live the rest of your life as a champion. – Muhammad Ali" },
            { "quote": "Your time is limited, so don’t waste it living someone else’s life. – Steve Jobs" },
            { "quote": "Great things never come from comfort zones. – Anonymous" },
            { "quote": "The best way to get started is to quit talking and begin doing. – Walt Disney" },
            { "quote": "Success is walking from failure to failure with no loss of enthusiasm. – Winston Churchill" },
            { "quote": "Believe in the magic that’s within you. – Greyson Chance" },
            { "quote": "Your life does not get better by chance, it gets better by change. – Jim Rohn" },
            { "quote": "If you want to achieve greatness stop asking for permission. – Anonymous" },
            { "quote": "Be not afraid of life. Believe that life is worth living, and your belief will help create the fact. – William James" },
            { "quote": "If you can dream it, you can do it. – Walt Disney" },
            { "quote": "The only way to discover the limits of the possible is to go beyond them into the impossible. – Arthur C. Clarke" },
            { "quote": "You are braver than you believe, stronger than you seem, and smarter than you think. – A.A. Milne" },
            { "quote": "The biggest risk is not taking any risk. – Mark Zuckerberg" },
            { "quote": "You don’t have to be great to start, but you have to start to be great. – Zig Ziglar" },
            { "quote": "Don’t wait for opportunity. Create it. – Anonymous" },
            { "quote": "Success is liking yourself, liking what you do, and liking how you do it. – Maya Angelou" },
            { "quote": "The only journey is the one within. – Rainer Maria Rilke" },
            { "quote": "Do one thing every day that scares you. – Eleanor Roosevelt" },
            { "quote": "The best revenge is massive success. – Frank Sinatra" },
            { "quote": "The key to success is to focus on goals, not obstacles. – Anonymous" },
            { "quote": "Success is the best revenge for anything. – Ed Sheeran" },
            { "quote": "It’s not whether you get knocked down, it’s whether you get up. – Vince Lombardi" },
            { "quote": "The purpose of our lives is to be happy. – Dalai Lama" },
            { "quote": "Don’t be afraid to give up the good to go for the great. – John D. Rockefeller" },
            { "quote": "Good things come to those who wait, but better things come to those who work for it. – Anonymous" },
            { "quote": "I find that the harder I work, the more luck I seem to have. – Thomas Jefferson" },
            { "quote": "If you are not willing to risk the usual, you will have to settle for the ordinary. – Jim Rohn" },
            { "quote": "Success is the sum of small efforts, repeated day-in and day-out. – Robert Collier" },
            { "quote": "Success usually comes to those who are too busy to be looking for it. – Henry David Thoreau" },
            { "quote": "Dream bigger. Do bigger. – Anonymous" },
            { "quote": "Start each day with a positive thought and a grateful heart. – Roy T. Bennett" },
            { "quote": "The road to success and the road to failure are almost exactly the same. – Colin R. Davis" },
            { "quote": "Don’t be distracted by criticism. Remember—the only taste of success some people have is when they take a bite out of you. – Zig Ziglar" },
            { "quote": "The only way to achieve the impossible is to believe it is possible. – Charles Kingsleigh" },
            { "quote": "You must expect great things of yourself before you can do them. – Michael Jordan" },
            { "quote": "You are the artist of your own life. Don’t hand the paintbrush to anyone else. – Anonymous" },
            { "quote": "It’s never too late to be what you might have been. – George Eliot" },
            
                { "quote": "Your life does not get better by chance, it gets better by change. – Jim Rohn" },
                { "quote": "The only person you are destined to become is the person you decide to be. – Ralph Waldo Emerson" },
                { "quote": "If you want something you’ve never had, you must be willing to do something you’ve never done. – Thomas Jefferson" },
                { "quote": "The best revenge is massive success. – Frank Sinatra" },
                { "quote": "Don’t let the noise of others’ opinions drown out your own inner voice. – Steve Jobs" },
                { "quote": "It does not matter how slowly you go as long as you do not stop. – Confucius" },
                { "quote": "Success is not the absence of failure; it’s the persistence through failure. – Aisha Tyler" },
                { "quote": "Don’t be afraid to give up the good to go for the great. – John D. Rockefeller" },
                { "quote": "You are never too old to set another goal or to dream a new dream. – C.S. Lewis" },
                { "quote": "Everything you’ve ever wanted is on the other side of fear. – George Addair" },
                { "quote": "The only limit to our realization of tomorrow is our doubts of today. – Franklin D. Roosevelt" },
                { "quote": "Start where you are. Use what you have. Do what you can. – Arthur Ashe" },
                { "quote": "The only way to achieve the impossible is to believe it is possible. – Charles Kingsleigh" },
                { "quote": "We may encounter many defeats but we must not be defeated. – Maya Angelou" },
                { "quote": "You don’t have to be great to start, but you have to start to be great. – Zig Ziglar" },
                { "quote": "The harder you work for something, the greater you’ll feel when you achieve it. – Unknown" },
                { "quote": "Dream it. Wish it. Do it. – Unknown" },
                { "quote": "Success doesn’t just find you. You have to go out and get it. – Unknown" },
                { "quote": "The key to success is to focus on goals, not obstacles. – Unknown" },
                { "quote": "Dream bigger. Do bigger. – Unknown" },
                { "quote": "Don’t stop when you’re tired. Stop when you’re done. – Unknown" },
                { "quote": "Wake up with determination. Go to bed with satisfaction. – Unknown" },
                { "quote": "Do something today that your future self will thank you for. – Unknown" },
                { "quote": "Little things make big days. Great things take time. Be patient. – Unknown" },
                { "quote": "It’s going to be hard, but hard does not mean impossible. – Unknown" },
                { "quote": "Push yourself, because no one else is going to do it for you. – Unknown" },
                { "quote": "Great things never come from comfort zones. – Unknown" },
                { "quote": "Dream it. Believe it. Build it. – Unknown" },
                { "quote": "Don’t wait for opportunity. Create it. – Unknown" },
                { "quote": "The key to success is to focus on goals, not obstacles. – Unknown" },
                { "quote": "Dream it. Wish it. Do it. – Unknown" },
                { "quote": "Success doesn’t just find you. You have to go out and get it. – Unknown" },
                { "quote": "Work hard in silence, let your success be your noise. – Frank Ocean" },
                { "quote": "Rise above the storm and you will find the sunshine. – Mario Fernandez" },
                { "quote": "Don’t be afraid to give up the good to go for the great. – John D. Rockefeller" },
                { "quote": "I find that the harder I work, the more luck I seem to have. – Thomas Jefferson" },
                { "quote": "Success is not the absence of failure; it’s the persistence through failure. – Aisha Tyler" },
                { "quote": "Hardships often prepare ordinary people for an extraordinary destiny. – C.S. Lewis" },
                { "quote": "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. – Christian D. Larson" },
                { "quote": "The future belongs to those who believe in the beauty of their dreams. – Eleanor Roosevelt" },
                { "quote": "You are never too old to set another goal or to dream a new dream. – C.S. Lewis" },
                { "quote": "The only way to achieve the impossible is to believe it is possible. – Charles Kingsleigh" },
                { "quote": "Success is going from failure to failure without losing your enthusiasm. – Winston Churchill" },
                { "quote": "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart. – Roy T. Bennett" },
                { "quote": "The best time to plant a tree was 20 years ago. The second best time is now. – Chinese Proverb" },
                { "quote": "The only limit to our realization of tomorrow is our doubts of today. – Franklin D. Roosevelt" },
                { "quote": "Don’t let yesterday take up too much of today. – Will Rogers" },
                { "quote": "You do not find the happy life. You make it. – Camilla E. Kimball" },
                { "quote": "The only way to do great work is to love what you do. – Steve Jobs" },
                { "quote": "Success usually comes to those who are too busy to be looking for it. – Henry David Thoreau" },
                { "quote": "Don’t watch the clock; do what it does. Keep going. – Sam Levenson" },
                { "quote": "The future belongs to those who believe in the beauty of their dreams. – Eleanor Roosevelt" },
                { "quote": "The only way to achieve the impossible is to believe it is possible. – Charles Kingsleigh" },
                { "quote": "Hardships often prepare ordinary people for an extraordinary destiny. – C.S. Lewis" },
                { "quote": "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. – Christian D. Larson" },
                { "quote": "The future belongs to those who believe in the beauty of their dreams. – Eleanor Roosevelt" },
                { "quote": "You are never too old to set another goal or to dream a new dream. – C.S. Lewis" },
              
                
                    { "quote": "Success is not the destination; it's the journey. – Zig Ziglar" },
                    { "quote": "The secret of success is to do the common thing uncommonly well. – John D. Rockefeller Jr." },
                    { "quote": "Success is how high you bounce when you hit bottom. – George S. Patton" },
                    { "quote": "The road to success is always under construction. – Lily Tomlin" },
                    { "quote": "Success is achieved and maintained by those who try and keep trying. – W. Clement Stone" },
                    { "quote": "Success is getting what you want. Happiness is wanting what you get. – Ingrid Bergman" },
                    { "quote": "Action is the foundational key to all success. – Pablo Picasso" },
                    { "quote": "Success is the result of preparation, hard work, and learning from failure. – Colin Powell" },
                    { "quote": "The way to get started is to quit talking and begin doing. – Walt Disney" },
                    { "quote": "Success is not in what you have, but who you are. – Bo Bennett" },
                    { "quote": "Success is the progressive realization of a worthy goal or ideal. – Earl Nightingale" },
                    { "quote": "Success is a state of mind. If you want success, start thinking of yourself as a success. – Joyce Brothers" },
                    { "quote": "Success is stumbling from failure to failure with no loss of enthusiasm. – Winston Churchill" },
                    { "quote": "The path to success is to take massive, determined action. – Tony Robbins" },
                    { "quote": "Success comes from knowing that you did your best to become the best that you are capable of becoming. – John Wooden" },
                    { "quote": "Success is the doing, not the getting; in the trying, not the triumph. – Zig Ziglar" },
                    { "quote": "Success is when preparation meets opportunity. – Bobby Unser" },
                    { "quote": "Success is 1% inspiration, 99% perspiration. – Thomas Edison" },
                    { "quote": "Success is simple. Do what's right, the right way, at the right time. – Arnold H. Glasow" },
                    { "quote": "Success is the ability to go from failure to failure without losing your enthusiasm. – Winston Churchill" },
                    { "quote": "Success is not just making money. It's making a difference. – Anonymous" },
                    { "quote": "Success seems to be connected with action. Successful people keep moving. They make mistakes, but they don’t quit. – Conrad Hilton" },
                    { "quote": "Success is the sum of small efforts, repeated day in and day out. – Robert Collier" },
                    { "quote": "The key to success is to focus on goals, not obstacles. – Anonymous" },
                    { "quote": "The ladder of success is best climbed by stepping on the rungs of opportunity. – Ayn Rand" },
                    { "quote": "Success is doing ordinary things extraordinarily well. – Jim Rohn" },
                    { "quote": "Success is not to be pursued; it is to be attracted by the person you become. – Jim Rohn" },
                    { "quote": "Success is about creating value, not just wealth. – Steve Forbes" },
                    { "quote": "Success is walking from failure to failure with no loss of enthusiasm. – Winston Churchill" },
                    { "quote": "Success is getting what you want, happiness is wanting what you get. – W. P. Kinsella" },
                    { "quote": "Success isn't just about what you accomplish in your life; it's about what you inspire others to do. – Anonymous" },
                    { "quote": "Success isn't always about greatness. It's about consistency. Consistent hard work leads to success. – Dwayne Johnson" },
                    { "quote": "Success is a journey, not a destination. The doing is often more important than the outcome. – Arthur Ashe" },
                    { "quote": "The real test is not whether you avoid this failure, because you won’t. It’s whether you let it harden or shame you into inaction, or whether you learn from it; whether you choose to persevere. – Barack Obama" },
                    { "quote": "Success is the sum of small efforts, repeated day in and day out. – Robert Collier" },
                    { "quote": "Success in life comes not from holding a good hand, but in playing a poor hand well. – Denis Waitley" },
                    { "quote": "Success is not in what you have, but who you are. – Bo Bennett" },
                    { "quote": "Success is a science; if you have the conditions, you get the result. – Oscar Wilde" },
                    { "quote": "Success is not just making money. It’s making a difference. – Anonymous" },
                    { "quote": "Success is often achieved by those who don’t know that failure is inevitable. – Coco Chanel" },
                    { "quote": "The secret of success is to know something nobody else knows. – Aristotle Onassis" },
                    { "quote": "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. – Albert Schweitzer" },
                    { "quote": "Success is more a function of consistent common sense than it is of genius. – An Wang" },
                    { "quote": "Success comes in cans; failure in can'ts. – Anonymous" },
                    { "quote": "Success does not consist in never making mistakes but in never making the same one a second time. – George Bernard Shaw" },
                    { "quote": "The secret of success is constancy of purpose. – Benjamin Disraeli" },
                    { "quote": "Success isn't something that just happens – success is learned, success is practiced and then it is shared. – Sparky Anderson" },
                    { "quote": "Success means doing the best we can with what we have. Success is the doing, not the getting; in the trying, not the triumph. Success is a personal standard, reaching for the highest that is in us, becoming all that we can be. – Zig Ziglar" },
                    { "quote": "The true success is the person who invented himself. – Al Goldstein" },
                    
                        { "quote": "Money is a terrible master but an excellent servant. – P.T. Barnum" },
                        { "quote": "The lack of money is the root of all evil. – Mark Twain" },
                        { "quote": "It’s not about how much money you make. It’s about how much money you keep. – Robert Kiyosaki" },
                        { "quote": "The goal isn’t more money. The goal is living life on your terms. – Chris Brogan" },
                        { "quote": "Money often costs too much. – Ralph Waldo Emerson" },
                        { "quote": "Money won’t create success, the freedom to make it will. – Nelson Mandela" },
                        { "quote": "The rich invest in time, the poor invest in money. – Warren Buffett" },
                        { "quote": "Wealth consists not in having great possessions, but in having few wants. – Epictetus" },
                        { "quote": "Your income is directly related to your philosophy, not the economy. – Jim Rohn" },
                        { "quote": "The lack of money is no obstacle. The lack of an idea is an obstacle. – Ken Hakuta" },
                        { "quote": "The more you learn, the more you earn. – Warren Buffett" },
                        { "quote": "When I had money everyone called me brother. – Polish proverb" },
                        { "quote": "Money is a good servant but a poor master. – Francis Bacon" },
                        { "quote": "Success is not just about making money. It’s about making a difference. – Unknown" },
                        { "quote": "Never spend your money before you have earned it. – Thomas Jefferson" },
                        { "quote": "If you want to be rich, think big. – Donald Trump" },
                        { "quote": "The only wealth which you will keep forever is the wealth you have given away. – Marcus Aurelius" },
                        { "quote": "A penny saved is a penny earned. – Benjamin Franklin" },
                        { "quote": "Money is a tool. Used properly it makes something beautiful; used wrongly, it makes a mess! – Bradley Vinson" },
                        { "quote": "Financial freedom is freedom from fear. – Robert Kiyosaki" },
                        { "quote": "The goal of the rich is not just to have money but to create value. – Unknown" },
                        { "quote": "You don’t have to be rich to be generous. – Unknown" },
                        { "quote": "Money can’t buy happiness, but it can buy you the freedom to find it. – Unknown" },
                        { "quote": "The best way to predict your future is to create it. – Peter Drucker" },
                        { "quote": "Your wealth can be stolen, but the knowledge you’ve gained can never be taken. – Unknown" },
                        { "quote": "Money grows on the tree of persistence. – Japanese proverb" },
                        { "quote": "The best investment you can make is in yourself. – Warren Buffett" },
                        { "quote": "When you have money, think about your future. When you don’t have money, think about your present. – Unknown" },
                        { "quote": "The rich get richer, and the poor get poorer. – Unknown" },
                        { "quote": "If you want to be successful, you need to stop being afraid of taking risks. – Unknown" },
                        { "quote": "Money is not everything, but it ranks right up there with oxygen. – Unknown" },
                        { "quote": "To be rich is not the end goal; to live a life of integrity is. – Unknown" },
                        { "quote": "The only way to do great work is to love what you do. – Steve Jobs" },
                        { "quote": "Being rich is having money; being wealthy is having time. – Stephen R. Covey" },
                        { "quote": "The rich are those who have accumulated assets that generate passive income. – Robert Kiyosaki" },
                        { "quote": "Money can’t buy happiness, but it can buy you the things that make you happy. – Unknown" },
                        { "quote": "Happiness is not in money, but in the joy of achievement. – Franklin D. Roosevelt" },
                        { "quote": "Your financial situation does not determine your happiness. – Unknown" },
                        { "quote": "Money doesn’t change people; it changes the people around them. – Unknown" },
                        { "quote": "To achieve financial freedom, you must stop trading your time for money. – Unknown" },
                        { "quote": "Earn money while you sleep. – Unknown" },
                        { "quote": "The way to wealth is to learn and act on the principles of wealth. – Unknown" },
                        { "quote": "Money is a great servant but a terrible master. – Francis Bacon" },
                        { "quote": "If you live for having it all, what you have is never enough. – Vicki Robin" },
                        { "quote": "Financial freedom is not about having money, it’s about having choices. – Unknown" },
                        { "quote": "A good reputation and a long life are invaluable assets. – Unknown" },
                        { "quote": "Making money is art and working is art and good business is the best art. – Andy Warhol" },
                        { "quote": "It’s not how much money you make, but how much money you keep that counts. – Robert Kiyosaki" },
                        { "quote": "Money often costs too much. – Ralph Waldo Emerson" },
                        { "quote": "The true measure of your wealth is how much you’d be worth if you lost all your money. – Unknown" },
                        { "quote": "If you want to achieve greatness, stop asking for permission. – Unknown" },
                        { "quote": "Money can’t buy happiness, but it can buy freedom, which is the key to happiness. – Unknown" },
                        { "quote": "Money is like a sixth sense – and you can’t make use of the other five without it. – William Somerset Maugham" },
                        { "quote": "The only thing money gives you is the freedom to not worry about money. – Johnny Depp" },
                        { "quote": "You must gain control over your money or the lack of it will forever control you. – Dave Ramsey" },
                        { "quote": "The best way to double your money is to fold it over and put it back in your pocket. – Will Rogers" },
                        { "quote": "Financial freedom is freedom from fear. – Robert Kiyosaki" },
                        { "quote": "The secret to wealth is to keep a positive mindset. – Unknown" },
                        { "quote": "Money is a terrible master but an excellent servant. – P.T. Barnum" },
                        { "quote": "Being rich is having money; being wealthy is having time. – Stephen R. Covey" },
                        { "quote": "The rich invest in time, the poor invest in money. – Warren Buffett" },
                        { "quote": "It’s not about having the money; it’s about having the right mindset. – Unknown" },
                        { "quote": "Money doesn’t change who you are, it just amplifies it. – Unknown" },
                        { "quote": "Money is a tool that can help you create the life you want. – Unknown" },
                        { "quote": "A budget is telling your money where to go instead of wondering where it went. – Dave Ramsey" },
                        { "quote": "Money can’t buy happiness, but it can buy freedom, which is the key to happiness. – Unknown" },
                        { "quote": "Your wealth is a reflection of your financial habits. – Unknown" },
                        { "quote": "The more you save, the more you’ll have. – Unknown" },
                        { "quote": "Invest in yourself. Your career is the engine of your wealth. – Paul Clitheroe" },
                        { "quote": "Money is a great servant but a terrible master. – Francis Bacon" },
                        { "quote": "If you want to be wealthy, learn from those who are wealthy. – Unknown" },
                        { "quote": "The less you spend, the more you save. – Unknown" },
                        { "quote": "If you don’t find a way to make money while you sleep, you will work until you die. – Warren Buffett" },
                        { "quote": "Success is the ability to go from one failure to another with no loss of enthusiasm. – Winston Churchill" },
                        { "quote": "The best investment you can make is in yourself. – Warren Buffett" },
                        { "quote": "Money doesn’t buy happiness, but it does buy options. – Unknown" },
                        { "quote": "It’s not how much money you make, it’s how much money you keep that counts. – Robert Kiyosaki" },
                        { "quote": "If you want to achieve financial freedom, you need to invest wisely. – Unknown" },
                        { "quote": "Money is a good servant but a poor master. – Francis Bacon" },
                        { "quote": "To get rich, you need to make money work for you. – Unknown" }
                      ]
                      
                  
 export default quotesArray;